name: sync

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: examples
      - uses: actions/checkout@v3
        with:
          repository: pipe-cd/pipecd
          path: pipecd
      - run: |
          cd pipecd
          git rev-parse HEAD > HEAD.txt
          cd ../examples
          rm -rf kubernetes
          cp -rf ../pipecd/examples/kubernetes .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "Sync with the examples directory in pipe-cd/pipecd repository"
